# list of tags and method of BS4 and it functionallity

In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [16]:
%%html
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>
<h3><b id='bol
    dest'>Lebron James</b></h3>
<p> Salary: $ 92,000,000 </p>
<h3> Stephen Curry</h3>
<p> Salary: $85,000, 000 </p>
<h3> Kevin Durant </h3>
<p> Salary: $73,200, 000</p>
</body>
</html>

In [15]:
html="<!DOCTYPE html><html><head><title>Page Title</title></head><body><h3><b id='boldest'>Lebron James</b></h3><p> Salary: $ 92,000,000 </p><h3> Stephen Curry</h3><p> Salary: $85,000, 000 </p><h3> Kevin Durant </h3><p> Salary: $73,200, 000</p></body></html>"

In [17]:
# Parse the HTML
soup = BeautifulSoup(html, 'html.parser')

In [23]:
print(soup.prettify()) # print the parsed data of html

<!DOCTYPE html>
<html>
 <head>
  <title>
   Page Title
  </title>
 </head>
 <body>
  <h3>
   <b id="boldest">
    Lebron James
   </b>
  </h3>
  <p>
   Salary: $ 92,000,000
  </p>
  <h3>
   Stephen Curry
  </h3>
  <p>
   Salary: $85,000, 000
  </p>
  <h3>
   Kevin Durant
  </h3>
  <p>
   Salary: $73,200, 000
  </p>
 </body>
</html>

In [24]:
soup.text

'Page TitleLebron James Salary: $ 92,000,000  Stephen Curry Salary: $85,000, 000  Kevin Durant  Salary: $73,200, 000'

# Tags
- `soup.title` : returns the title of the page
- `soup.title.name` : returns the name of the title tag
- `soup.title.string` : returns the string inside the title tag
- `soup.p` : returns the first p tag
- `soup.p['class']` : returns the class of the p tag
- `soup.a` : returns the first a tag
- `soup.find_all('a')` : returns all the a tags
- `soup.find(id='link3')` : returns the tag with id link3
- `soup.get_text()` : returns the text of the page
- `soup.get_text(strip=True)` : returns the text of the page without the extra spaces
- `soup.get_text(strip=False)` : returns the text of the page with the extra spaces
- `soup.get_text(separator=' ')` : returns the text of the page with the separator as space
- `soup.get_text(separator='-', strip=True)` : returns the text of the page with the separator as - and without the extra spaces    
- `soup.get_text(separator='-', strip=False)` : returns the text of the page with the separator as - and with the extra spaces

In [25]:
soup.title

In [26]:
soup.title.name

'title'

In [27]:
soup.title.string

'Page Title'

In [28]:
soup.title.parent.name

'head'

In [29]:
soup.title.previous_element

In [30]:
soup.title.previous_siblings

In [31]:
soup.title.next

'Page Title'

In [33]:
soup.title.next_element

'Page Title'

In [34]:
soup.title.next_sibling

In [35]:
soup.head

In [36]:
soup.head.next_sibling

In [38]:
soup.head.next_sibling.next_element

In [40]:
soup.body.get_text()

'Lebron James Salary: $ 92,000,000  Stephen Curry Salary: $85,000, 000  Kevin Durant  Salary: $73,200, 000'

In [41]:
soup.h3

In [46]:
soup.find_all('h3')

[<h3><b id="boldest">Lebron James</b></h3>,
 <h3> Stephen Curry</h3>,
 <h3> Kevin Durant </h3>]

In [47]:
soup.find_all('p')

[<p> Salary: $ 92,000,000 </p>,
 <p> Salary: $85,000, 000 </p>,
 <p> Salary: $73,200, 000</p>]

In [53]:
soup.find_all('h3')[0].get_text()

'Lebron James'

## Tags

In [54]:
tag_object=soup.find_all('h3')[0]

In [55]:
print(tag_object)

<h3><b id="boldest">Lebron James</b></h3>

In [56]:
print(type(tag_object))

<class 'bs4.element.Tag'>

In [58]:
tag_object=soup.h3
tag_object

In [59]:
tag_object.b

### Children, Parents, and Siblings

In [62]:
tag_chiled = tag_object.b
tag_chiled

In [63]:
tag_object.parent